columns_of_interest:
  -
    Year
  -
    Month
  -
    DayofMonth
  -
    DayOfWeek
  -
    Reporting_Airline
  -
    Tail_Number
  -
    Flight_Number_Reporting_Airline
  -
    Origin
  -
    OriginCityName
  -
    OriginStateName
  -
    Dest
  -
    DestCityName
  -
    DestStateName
  -
    DepTime
  -
    DepDelay
  -
    AirTime
  -
    Distance